### ISSUE TITLE
Proguard warning in app if not using lombok

### ISSUE THREAD

**Issue by lfielke** [NextFaze/power-adapters#35]
If an Android app depends on power-adapters but doesn't have a compile dependency on lombok, then proguard will fail with a warning that referenced class `lombok.NonNull` is not found. This is a spurious warning because the annotation is pointless at runtime, but it causes proguard to error the build.

This could be fixed by including a proguard consumer "proguard.txt" file with a line:
```
-dontwarn lombok.NonNull
```
and configuring
```
defaultConfig {
    consumerProguardFiles 'proguard.txt'
}
```

**Comment by btilbrook-nextfaze** [comment]
I think I'll probably replace Lombok `@NonNull` with support annotation `@NonNull` anyway.
