### ISSUE TITLE
Example on how to sort Data?

### ISSUE THREAD

**Issue by cheneveld** [NextFaze/power-adapters#37]
The only place I could find "sort" in the code base was in tests that was testing private functionality.

I am creating a Data<Object> via ObservableDataBuilder ->

```
@Override
    protected Data<?> getDataLoader() {
            ObservableDataBuilder<Player> dataBuilder = new ObservableDataBuilder<>();

            dataBuilder.contents(
                    DataApi.getDataObservable()
            );

            return dataBuilder.build();
    }
```

Given a that instantiated instance of a Data<?>, how can one sort the underlying data?

I see a sort method here -> [https://github.com/NextFaze/power-adapters/blob/752e3968f20740949a4f48c7590b9ff6acde7eb9/power-adapters-data/src/main/java/com/nextfaze/poweradapters/data/Data.java#L467](url).

I couldn't seem to create a proper comparator to pass to that method.

Also, I wasn't sure if calling that method takes care of the rest, updating a notifying observables?

**Comment by btilbrook-nextfaze** [comment]
Since you're using an `Observable<T>` (best way to handle it!), I recommend sorting that:

```
DataApi.getDataObservable().map(list -> Collections.sort(list, <your comparator>))
```

While the `Data<T>` class _does_ have a `sort` fluent method, I no longer recommend it, since it sorts on the main thread, and therefore isn't suitable for larger datasets.

**Comment by cheneveld** [comment]
Ok, this is what I am actually doing, but was hoping sorting the data already in the adapter would keep me from hitting the api again.  But that's ok.

Thanks!
